condense_wildcard_suffixes = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
format_code_in_doc_comments = true
format_strings = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
