# Rust analyzer for VSCode still seems to need this...
cargo-features = ["edition2024"]

[package]
name = "ultimate-mod-man-rs-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
