[package]
name = "ultimate-mod-man-rs-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
ultimate-mod-man-rs-core = { path = "../core" }

anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
dirs = "6.0.0"
log = "0.4.22"
