[package]
name = "ultimate-mod-man-rs-scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.12"
scraper = "0.22.0"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
