[package]
name = "ultimate-mod-man-rs-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
camino = "1.1.9"
derive_builder = "0.20.2"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
toml = "0.8.20"
